### PR TITLE
3.0/list broken

### PR DESCRIPTION
**Pull request by silvergrund**
Fixed Display of data,
Hide template before placeholders are populated
enque css, 
typos in Webpack,
Accordion icons
paddings
responsive table
etc etc

### CODE REVIEW

**Comment by sebastianthulin** [comment]
Missing buildscript.

**Comment by sebastianthulin** [comment]
Remove dist-files.

**Comment by silvergrund** [comment]
> Missing buildscript.

fixat...

**Comment by silvergrund** [comment]
> Remove dist-files.

fixat.

**Pull request merged**
